#!/bin/bash
# CC Orchestrator - Project Initialization Script
# Usage: ./init_project.sh <project_name> [base_dir]

set -e

PROJECT_NAME="${1:-my_project}"
BASE_DIR="${2:-.}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RANDOM_ID=$(head /dev/urandom | tr -dc 'a-z0-9' | head -c 6)
PROJECT_DIR="${BASE_DIR}/${PROJECT_NAME}_${TIMESTAMP}"

echo "🚀 Initializing CC Orchestrator Project"
echo "   Project: ${PROJECT_NAME}"
echo "   Location: ${PROJECT_DIR}"
echo ""

# Create directory structure
echo "📁 Creating directory structure..."
mkdir -p "${PROJECT_DIR}"/{.orchestrator,requirements,specs,architecture,src,tests,docs}

# Initialize state.json
echo "📋 Initializing state.json..."
cat > "${PROJECT_DIR}/.orchestrator/state.json" << EOF
{
  "project_id": "proj_${TIMESTAMP}_${RANDOM_ID}",
  "project_name": "${PROJECT_NAME}",
  "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "user_request": null,
  "config": {
    "dreamer_critic_rounds": 3,
    "pm_techlead_rounds": 2,
    "dev_review_rounds": 3,
    "max_developers": 5
  },
  "current_phase": "init",
  "current_round": 0,
  "developer_count": null,
  "developer_assignments": {},
  "phases": {
    "init": {"status": "pending"},
    "requirements": {"status": "pending", "current_round": 0},
    "specs": {"status": "pending", "current_round": 0},
    "architecture": {"status": "pending"},
    "test_planning": {"status": "pending"},
    "development": {"status": "pending"},
    "verification": {"status": "pending"},
    "delivery": {"status": "pending"}
  },
  "artifacts": {},
  "errors": [],
  "task_log": []
}
EOF

# Create placeholder files
echo "📝 Creating placeholder files..."
echo "# Requirements" > "${PROJECT_DIR}/requirements/.gitkeep"
echo "# Specifications" > "${PROJECT_DIR}/specs/.gitkeep"
echo "# Architecture" > "${PROJECT_DIR}/architecture/.gitkeep"
echo "# Source Code" > "${PROJECT_DIR}/src/.gitkeep"
echo "# Tests" > "${PROJECT_DIR}/tests/.gitkeep"
echo "# Documentation" > "${PROJECT_DIR}/docs/.gitkeep"

# Create project README
cat > "${PROJECT_DIR}/README.md" << EOF
# ${PROJECT_NAME}

Created by CC Orchestrator on $(date)

## Project Structure

\`\`\`
${PROJECT_NAME}/
├── .orchestrator/     # Orchestration state
│   └── state.json    
├── requirements/      # Requirements phase outputs
├── specs/            # Specification phase outputs
├── architecture/     # Architecture phase outputs
├── src/              # Implementation
├── tests/            # Test files
└── docs/             # Documentation
\`\`\`

## Status

Check \`.orchestrator/state.json\` for current progress.

## Generated By

CC Orchestrator - Autonomous Multi-Agent Development System
EOF

echo ""
echo "✅ Project initialized successfully!"
echo ""
echo "📂 Project location: ${PROJECT_DIR}"
echo ""
echo "Next steps:"
echo "  1. cd ${PROJECT_DIR}"
echo "  2. Start Claude Code: claude"
echo "  3. Invoke: @cc-orchestrator/agents/MANAGER.md <your request>"
echo ""
